// <auto-generated />
using BlazorServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServer.Migrations.DictionaryDb
{
    [DbContext(typeof(DictionaryDbContext))]
    [Migration("20231110144041_ChangedTranslationTables")]
    partial class ChangedTranslationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Objects.Entities.Translator.TranslatorWordResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplaySource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Objects.Entities.Translator.WordTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("DisplayTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefixWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("Translations");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Objects.Entities.Translator.TranslationEnglish", b =>
                {
                    b.HasBaseType("Objects.Entities.Translator.WordTranslation");

                    b.ToTable("TranslationsEnglish", (string)null);
                });

            modelBuilder.Entity("Objects.Entities.Translator.TranslationGerman", b =>
                {
                    b.HasBaseType("Objects.Entities.Translator.WordTranslation");

                    b.ToTable("TranslationsGerman", (string)null);
                });

            modelBuilder.Entity("Objects.Entities.Translator.TranslationRussian", b =>
                {
                    b.HasBaseType("Objects.Entities.Translator.WordTranslation");

                    b.ToTable("TranslationsRussian", (string)null);
                });

            modelBuilder.Entity("Objects.Entities.Translator.WordTranslation", b =>
                {
                    b.HasOne("Objects.Entities.Translator.TranslatorWordResponse", null)
                        .WithMany("Translations")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Objects.Entities.Translator.TranslationEnglish", b =>
                {
                    b.HasOne("Objects.Entities.Translator.WordTranslation", null)
                        .WithOne()
                        .HasForeignKey("Objects.Entities.Translator.TranslationEnglish", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Objects.Entities.Translator.TranslationGerman", b =>
                {
                    b.HasOne("Objects.Entities.Translator.WordTranslation", null)
                        .WithOne()
                        .HasForeignKey("Objects.Entities.Translator.TranslationGerman", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Objects.Entities.Translator.TranslationRussian", b =>
                {
                    b.HasOne("Objects.Entities.Translator.WordTranslation", null)
                        .WithOne()
                        .HasForeignKey("Objects.Entities.Translator.TranslationRussian", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Objects.Entities.Translator.TranslatorWordResponse", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
